name: llms
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - python-dotenv
  - requests
  - beautifulsoup4
  - pydub
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - ipywidgets
  - pyarrow
  - anthropic
  - google-generativeai
  - matplotlib
  - scikit-learn
  - chromadb
  - langchain
  - langchain-text-splitters
  - langchain-openai
  - langchain-experimental
  - langchain-chroma
  - faiss-cpu
  - tiktoken
  - jupyter-dash
  - plotly
  - twilio
  - duckdb
  - feedparser
  - pip:
    - transformers
    - sentence-transformers
    - datasets
    - accelerate
    - sentencepiece
    - bitsandbytes
    - openai
    - gradio
    - gensim
    - modal
    - ollama